name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: documentation/yarn.lock  # Add this line

      - name: Install dependencies
        working-directory: ./documentation  # Add this line
        run: yarn install --frozen-lockfile
        
      - name: Build website
        working-directory: ./documentation  # Add this line
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation/build  # Update this path

  deploy:
    # Rest of the deploy job remains the same
