# .github/workflows/trigger-docs-ci.yml
name: Trigger Docs CI

on:
  push:
    branches:
      - main

jobs:
  trigger-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout docs branch
        uses: actions/checkout@v2
        with:
          ref: docs
          path: docs

      - name: Run Next.js CI
        run: |
          cd docs/.github/workflows
          # Executa o workflow nextjs.yml
          # Aqui você pode adicionar o comando para executar o CI, se necessário
          echo "Executando o CI do Next.js"